apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "0s"
        autoscaling.knative.dev/target-burst-capacity: "-1"
        autoscaling.knative.dev/window: "12s"
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/target: "10"
    spec:
      containerConcurrency: 1 # default is 0, means unlimited
      # schedulerName: bonano-scheduler
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node1
      containers:
      - image: docker.io/bonavadeur/shuka:v1.3
        resources:
          limits:
            cpu: 500m
            memory: 640M
        env:
        - name: TARGET
          value: "Konnichiwa >o<''"
        - name: THREADS
          value: "1"
